#!/usr/bin/env bash

echo "[+] Cleaning"

rm -rf bin
mkdir bin

if [ ! -d "MarkdownHS" ] ; then
  echo "[+] Downloading MDHS"
  git clone git@github.com:jawline/MarkdownHS.git
  (cd MarkdownHS; git pull; make)
fi

echo "[+] Building"

./MarkdownHS/bin/main "./sources/" "./bin/"
